[package]
name = "ic-websocket-cdk"
version = "0.2.0"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
description = "IC Websocket Canister Development Kit"
homepage = "https://docs.rs/ic-websocket-cdk"
documentation = "https://docs.rs/ic-websocket-cdk"
readme = "../../README.md"
exclude = [
  "**/*.did",
]

[dependencies]
candid = { workspace = true }
ic-cdk = { workspace = true }
ic-cdk-macros = { workspace = true }
ic-cdk-timers = "0.4.0"
serde = { workspace = true }
serde_cbor = { workspace = true }
ic-certified-map = "0.4.0"
base64 = "0.21.2"
sha2 = { workspace = true }
serde_bytes = "0.11.12"

[dev-dependencies]
ic-agent = "0.25.0"
proptest = "1.2.0"
rand = { workspace = true }
ring = "0.16.20"
lazy_static = "1.4.0"
pocket-ic = "1.0.0"
ic-certificate-verification = "1.2.0"
ic-certification = "1.2.0"

[package.metadata.docs.rs]
default-target = "wasm32-unknown-unknown"
