name: Publish ic-websocket-cdk-rs

# only run when a release is published
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: "stable"
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"
      - name: Publish on crates.io
        id: cargo-publish
        run: |
          rustup target add wasm32-unknown-unknown
          cargo publish -p ic-websocket-cdk
          echo "version=$(cargo pkgid -p ic-websocket-cdk | cut -d# -f2 | cut -d: -f2)" >> "$GITHUB_OUTPUT"
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
